services:
  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: alpha-crucible-backend
    environment:
      - DATABASE_URL=${DATABASE_URL}?sslmode=require
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PYTHONPATH=${PYTHONPATH}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "8000:8000"
    networks:
      - alpha-crucible-network
    restart: unless-stopped
    volumes:
      - ./src:/app/src:ro
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_URL=${API_BASE_URL}/api
    container_name: alpha-crucible-frontend
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - alpha-crucible-network
    restart: unless-stopped
    env_file:
      - .env

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: alpha-crucible-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - alpha-crucible-network
    restart: unless-stopped

networks:
  alpha-crucible-network:
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
        - subnet: 2001:db8::/64
          gateway: 2001:db8::1

