version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: alpha-crucible-backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=${DB_SSL_MODE}
    ports:
      - "8000:8000"
    networks:
      - alpha-crucible-network
    restart: unless-stopped
    volumes:
      - ./src:/app/src:ro

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: alpha-crucible-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - alpha-crucible-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: alpha-crucible-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - alpha-crucible-network
    restart: unless-stopped

networks:
  alpha-crucible-network:
    driver: bridge

